# Generated by Django 6.0.4 on 2026-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='codigo',
            field=models.CharField(default='esita', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
