# Generated by Django 6.0.4 on 2026-06-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disponibilidade_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='condutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_como_condutor', to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='profissionais',
            field=models.ManyToManyField(related_name='equipes_como_profissional', to='api.funcionario'),
        ),
    ]
