# Generated by Django 6.0.4 on 2026-06-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipe_condutor_alter_equipe_profissionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='paciente',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='nome_paciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='telefone_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='api.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oficina', models.CharField(blank=True, max_length=150, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='api.veiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
