# Generated by Django 6.0.4 on 2026-06-11 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_funcionario_veiculo_equipe_atribuida'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cnh',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='api.veiculo'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipo_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiporegistro'),
        ),
        migrations.AlterField(
            model_name='cnh',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnh', to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='condutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes_como_condutor', to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='api.veiculo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='condutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_como_condutor', to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipe'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veiculo'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_saude', to='api.funcionario'),
        ),
    ]
