# Generated by Django 6.0.4 on 2026-06-11 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_abastecimento_ativo_cnh_ativo_equipe_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('EM_MANUTENCAO', 'Em Manutenção'), ('FINALIZADA', 'Finalizada')], default='EM_MANUTENCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='api.funcionario'),
        ),
    ]
