# Generated by Django 6.0.4 on 2026-06-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_manutencao_status_alter_atendente_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='telefone_paciente',
        ),
    ]
