# Generated by Django 6.0.4 on 2026-05-05 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enfermeiro_equipe_chamado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='enfermeiro',
        ),
        migrations.AddField(
            model_name='equipe',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='enfermeiros',
            field=models.ManyToManyField(to='api.enfermeiro'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.equipe'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.veiculo'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.motorista'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='o CPF deve conter exatamente 11 digitos numericos', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
